import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./Providers";
import Head from "next/head";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Omegle: Talk to strangers!",
  description: "Generated by Pixover",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="description"
          content="Omegle.cm is a free online video chat start instant video chat with any female user you want using the Gomeet application. Chat live for free with Omegle.cm."
        />
        <meta
          name="keywords"
          content="Omegle.cm, Omegle, video chat, one-on-one chat, online chat, private chat, chat with strangers, chat 1v1, omegle video call, 1v1 meet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="index, follow" />
        <meta name="author" content="Omegle" />
        <meta property="og:title" content="Omegle: Talk to strangers!" />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://omegle-seven.vercel.app" />
        <meta property="og:site_name" content="Omegle.cm" />
        <meta
          property="og:description"
          content="Omegle.cm is a free online video chat start instant video chat with any female user you want using the Gomeet application. Chat live for free with Omegle.cm."
        />
        <link rel="canonical" href="https://omegle.online/gomeet/" />
        <link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico" />
        <meta name="msapplication-TileColor" content="#1d53a0" />
        <meta name="theme-color" content="#1d53a0" />
      </head>
      <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
